### ISSUE TITLE
about timer module, some advise

### ISSUE THREAD

**Issue by dogtapdsd** [juhlig/hnc#15]
Timer module was single gen_server process, when create massive process with hnc_pool gen_statem module. That will face a Bottleneck.
Using the gen_statem  Generic Time-Outs like "{keep_state, Data, [{{timeout,Ref},TimoutMs, TimeoutMsg}]}".
I think It was better option.

**Comment by Maria-12648430** [comment]
Thanks, we will look into it :)

**Comment by Maria-12648430** [comment]
https://github.com/erlang/otp/pull/4811 😉
